apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: vem-shop-frontend
  namespace: shop-pipelines
spec:
  serviceAccountName: pipeline
  triggers:
    - triggerRef: vem-shop-frontend-trigger