kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tekton-pvc
  namespace: shop-pipelines
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: tekton-sc
  volumeMode: Filesystem
